// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by Mobile.BuildTools. For more information or to
//      file an issue please see https://github.com/dansiegel/Mobile.BuildTools
//
//      Changes to this file may cause incorrect behavior and will be lost when 
//      the code is regenerated. 
//
//      NOTE: This file should be excluded from source control.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GreenEconomy.Core.Helpers
{
    internal static class Secrets
    {
        internal const string GoogleMapsKey = "AIzaSyA7mYrOr5RISAgUIDowtEoLA-cs64UZojE";

        internal const string GoogleGeocodeKey = "AIzaSyCmwIiI5B2_Ugta0xMKxh3YuumMzpFLh84";
    }
}
